---
title: "HW1 Sample"
output: html_document
---
```{r message=FALSE, warning=FALSE}
#install.packages('babynames')
library(babynames)
library(dplyr)
library(ggplot2)
```
# (c)
```{r}
plot1 <- babynames %>%
  filter(name == "Taylor") %>%
  ggplot(aes(x = year, y = n, col = sex))
plot1 + geom_line() + geom_point() + labs(title = "The Taylors")
```

# (d)

## i.
```{r}
babynames %>% filter(name == "Quinn", year == 2002)
```
## ii.
```{r}
babynames %>% filter(name == "Quinn", year == 2016)
```

```{r}
plot2 <- babynames %>%
  filter(name == "Quinn", year > 2000) %>%
  ggplot(aes(x = year, y = n, col = sex))
plot2 + geom_line() + geom_point() + 
  geom_vline(xintercept = c(2002, 2016), linetype = "dotted") + 
  labs(title = "The Quinns")
```

### iii.
```{r}
babynames %>%
  filter(name == "Susan", sex == "F") %>%
  filter(n == max(n))

plot3 <- babynames %>%
  filter(name == "Susan", sex == "F") %>%
  mutate(is_max = (n == max(n))) %>%
  ggplot(aes(x = year, y = n))
plot3 + geom_bar(aes(fill = is_max), stat = "identity", width = .7) + 
  labs(title = "The Female Susans")
```

or
```{r}
plot3 + geom_line() + geom_point() + 
  geom_vline(xintercept = 1955, linetype = "dotted") + 
  labs(title = "The Female Susans")
```